### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by Stavros963** [eliranwong/freegenius#14]
Hello, while not being a code specialist, I am interested in implementing freegenius for "real world" applications. It looks really great. However, when running the script, I get stuck into an "infinite loop". Can you help?

launching FreeGenius AI ...
Checking 'freegenius' version ...
Installed version: 0.2.7
Latest version: 0.2.19
pip tool updated!
Upgrading 'freegenius' ...
Package 'freegenius' upgraded!
Restarting FreeGenius AI ...
launching FreeGenius AI ...
Checking 'freegenius' version ...
Installed version: 0.2.7
Latest version: 0.2.19
pip tool updated!
Upgrading 'freegenius' ...

With my best regards!

**Comment by eliranwong** [comment]
Hi, may I ask if it works if you manually update:

> pip install freegenius==0.2.19

**Comment by eliranwong** [comment]
After closing the app and restart, it should work.
