### ISSUE TITLE
ASCII

### ISSUE THREAD

**Issue by fahdbitahi** [eliranwong/freegenius#17]
HEY, GREAT PROJECT BTW ! i was wondering if i can change the ascii art when i launch it to something costum ! thank you !

**Comment by eliranwong** [comment]
Okay, I will add an option for this

**Comment by eliranwong** [comment]
# Customise App Name Display

From version: 0.2.54

1. Enter '.editconfigs' in FreeGenius promptappName

2. Edit the following items:

appName

text2art_font1

text2art_font1

3. Save and Exit the built-in editor

**Comment by eliranwong** [comment]
uploaded https://github.com/eliranwong/freegenius/commit/963f0255eb6e892d7dff94ef899eb7c0473e0873

Thanks for suggestion.
