### ISSUE TITLE
initial launch - skip download

### ISSUE THREAD

**Issue by shuther** [eliranwong/freegenius#19]
I would like to skip downloading models (either working directly with ollama or with Groq), is it possible?
During the 1st launch, even if I provide the Groq key, it keeps installing the models?

l```
aunching FreeGenius AI ...
Checking 'freegenius' version ...
Installed version: 0.2.60
Latest version: 0.2.60
Old tool store removed!
# Groq Cloud API Key: allows access to Groq Cloud hosted LLMs
To set up Groq Cloud API Key, read:
https://github.com/eliranwong/freegenius/wiki/Set-up-a-Groq-Cloud-API-Key

Enter a single or a list of multiple Groq Cloud API Key(s) [optional]:

>>> ******
Downloading main model ...
codellama-7b-instruct.Q4_K_M.gguf:   2%|██▏                                                                                                      | 83.9M/4.08G [00:00<?, ?B/s]^CErrors! Restoring default main model!
Downloading main model ...
```

**Comment by eliranwong** [comment]
Okay, will add this option.  Thanks for suggestion.

**Comment by eliranwong** [comment]
Added -b or --backend cli options in https://github.com/eliranwong/freegenius/commit/4dc4551cfd212bed058cbba0079682d240c72972

start the app, e.g.:
> freegenius -b ollama

Please kindly let me know if it works or not.  Thanks.

**Comment by eliranwong** [comment]
fixed https://github.com/eliranwong/freegenius/commit/fe8bc084e42070febf72a7f59375e9d8b6b730e7 and tested.  It is working.  closing this issue now.

**Comment by eliranwong** [comment]
You can disable individual tools from action menu.
